apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.dbCredentials.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.dbCredentials.password | quote }}
  POSTGRES_DB: {{ .Values.dbCredentials.db | quote }}
