apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: resources-db
  namespace: {{ .Values.namespace }}
spec:
  serviceName: resources-db
  replicas: {{ .Values.replicaCount.resourcesDb }}
  selector:
    matchLabels:
      app: resources-db
  template:
    metadata:
      labels:
        app: resources-db
    spec:
      containers:
        - name: resources-db
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: db-credentials
          env:
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          volumeMounts:
            - name: resources-db-data
              mountPath: /var/lib/postgresql/data
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
          startupProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d postgres
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d postgres
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d postgres
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
      volumes:
        - name: initdb
          configMap:
            name: resources-db-initdb
  volumeClaimTemplates:
    - metadata:
        name: resources-db-data
      spec:
        storageClassName: {{ .Values.postgres.storageClassName }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.postgres.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: resources-db
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: resources-db
  ports:
    - port: 5432
      targetPort: 5432
