apiVersion: v1
kind: ConfigMap
metadata:
  name: resources-service-config
  namespace: {{ .Values.namespace }}
data:
  RESOURCES_DB_URL: "resources-db"
  RESOURCES_DB_PORT: "5432"
  RESOURCES_MS_PORT: "{{ .Values.resourcesService.containerPort }}"
  SONGS_MS_URL: "songs-service"
  SONGS_MS_PORT: "{{ .Values.songsService.containerPort }}"
  ENABLE_EUREKA_CLIENT: "false"
