apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: resources-db
  namespace: k8s-program
spec:
  serviceName: resources-db
  replicas: 1
  selector:
    matchLabels:
      app: resources-db
  template:
    metadata:
      labels:
        app: resources-db
    spec:
      containers:
        - name: resources-db
          image: postgres:latest
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: db-credentials
          env:
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          volumeMounts:
            - name: resources-db-data
              mountPath: /var/lib/postgresql/data
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: initdb
          configMap:
            name: resources-db-initdb
  volumeClaimTemplates:
    - metadata:
        name: resources-db-data
      spec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: resources-db
  namespace: k8s-program
spec:
  type: ClusterIP
  selector:
    app: resources-db
  ports:
    - port: 5432
      targetPort: 5432
