namespace: k8s-custom

replicaCount:
  resourcesService: 2
  songsService: 2
  resourcesDb: 1
  songsDb: 1

resourcesService:
  image: resources-image:v2
  imagePullPolicy: IfNotPresent
  containerPort: 8080

songsService:
  image: jossindev/songs-image:v2
  imagePullPolicy: IfNotPresent
  containerPort: 8081

postgres:
  image: postgres:latest
  storage: 1Gi
  storageClassName: standard

dbCredentials:
  user: postgres
  password: postgres
  db: postgres

ingress:
  enabled: true
  className: nginx
  host: ""
  rewriteTarget: /$1/$3
  paths:
    - path: /api/v1/(resources)(/|$)(.*)
      service: resources-service
      port: 8080
    - path: /api/v1/(songs)(/|$)(.*)
      service: songs-service
      port: 8081
